### ISSUE TITLE
ToDos for last week

### ISSUE THREAD

**Issue by msteiner96** [wynd-answers/wynd-app#18]
**Data Platform** 

- [x] Check endpoints
- [x] Script to update it daily (Ethan: hack to `systemctl restart api` every day at midnight... let's test)
- [x] Remove Alaska & Hawaii (opt.)
- [x] Switch out to Carbon Monoxide??
- [ ] Averaging / Normalization (opt)
- [ ] Make Index for multiple values (opt.)

**Contracts**

- [x] @msteiner96  sends a list to @ethanfrey about query information (withdraws)
- [x] Update for withdraw (Flag which ones are ready to withdraw/ Show what they get / Return how much was withdrawn etc.. / Events) 
- [x] Migrate existing contracts
- [x] Configure Secrets in local .env (not github)
- [x] Put the oracle fetch thingy in a cron
- [x] Redeploy
- [ ] Add data oracles (opt.)

**Frontend**

- [x] Update cosmjs to latest version
- [x] Paginate investements (right side)
- [x] Withdraw UX (Datatable)
- [x] @msteiner96 Invests on a few accounts now to test withdrawing later
- [x] About page / Link to readme
- [x] Reload Balance & Investment List after investing / withdrawing / etc

**Submitting**

- [x] Make repos public
- [x] Presentational video
- [x] Readme
- [ ] Some beautiful screenshots

**Comment by ethanfrey** [comment]
Guess we finished everything required and the optional issues remain for "later".

Last week is over, so closing. Great work!
